### ISSUE TITLE
Pam's HarvestCraft conflict

### ISSUE THREAD

**Issue by MJRamon** [Kashdeya/SimpleUpgrades#23]
**simpleupgrades-1.9-2.0.1-release
Pam's HarvestCraft 1.9b**

[22:44:13] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.NullPointerException
	at com.kashdeya.simpleupgrades.world.worldgen.runGenerator(worldgen.java:167) ~[worldgen.class:?]
	at com.kashdeya.simpleupgrades.world.worldgen.generate(worldgen.java:212) ~[worldgen.class:?]
	at net.minecraftforge.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:113) ~[GameRegistry.class:?]
	at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:998) ~[ase.class:?]
	at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:971) ~[ase.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.originalLoadChunk(ChunkProviderServer.java:175) ~[lo.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:126) ~[lo.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:96) ~[lo.class:?]
	at net.minecraft.world.World.func_72964_e(World.java:294) ~[aht.class:?]
	at net.minecraft.world.World.func_175726_f(World.java:289) ~[aht.class:?]
	at net.minecraft.world.World.func_180495_p(World.java:827) ~[aht.class:?]
	at net.minecraft.world.World.func_175623_d(World.java:214) ~[aht.class:?]
	at com.pam.harvestcraft.worldgen.LogFruitTreeWorldGen.generateShadedGarden(LogFruitTreeWorldGen.java:91) ~[LogFruitTreeWorldGen.class:?]
	at com.pam.harvestcraft.worldgen.LogFruitTreeWorldGen.generate(LogFruitTreeWorldGen.java:39) ~[LogFruitTreeWorldGen.class:?]
	at net.minecraftforge.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:113) ~[GameRegistry.class:?]
	at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:998) ~[ase.class:?]
	at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:980) ~[ase.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.originalLoadChunk(ChunkProviderServer.java:175) ~[lo.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:126) ~[lo.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:96) ~[lo.class:?]
	at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:295) ~[MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:173) ~[byn.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:196) ~[byn.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_91]

**Comment by Kashdeya** [comment]
Turn off the slat ore in simpleupgrades world config and you should be good to go.

**Comment by MJRamon** [comment]
No, it's not the case. Even then the same crash. As you can see, Harvestcraft is trying to create "LogFruitTreeWorldGen.generateShadedGarden"
Occures on world creation, tried several times.

**Comment by Kashdeya** [comment]
yeah i see that but i have nothing to do with pams code. nor do i have anything other then salt in my mod that would mess with pams code. so let me do some testing and see what i can come up with

**Comment by Kashdeya** [comment]
a push to curse has been made and will be out soon.
