### ISSUE TITLE
Client crash with NEI getting recipes that quartz ore is used in

### ISSUE THREAD

**Issue by HammerDave** [Kashdeya/SimpleUpgrades#40]
With NEI installed, hover on quartz ore, hit 'U' for use to get the recipes:

java.lang.ClassCastException: not an ItemStack, ItemStack[] or List<ItemStack?
	at codechicken.nei.util.NEIServerUtils.extractRecipeItems(NEIServerUtils.java:393)
	at codechicken.nei.api.stack.PositionedStack.<init>(PositionedStack.java:27)
	at codechicken.nei.api.stack.PositionedStack.<init>(PositionedStack.java:39)
	at codechicken.nei.recipe.ShapedRecipeHandler$CachedShapedRecipe.<init>(ShapedRecipeHandler.java:32)
	at codechicken.nei.recipe.ShapedRecipeHandler$CachedShapedRecipe.<init>(ShapedRecipeHandler.java:38)
	at codechicken.nei.recipe.ShapedRecipeHandler.loadUsageRecipes(ShapedRecipeHandler.java:140)
	at codechicken.nei.recipe.TemplateRecipeHandler.loadUsageRecipes(TemplateRecipeHandler.java:362)
	at codechicken.nei.recipe.TemplateRecipeHandler.getUsageHandler(TemplateRecipeHandler.java:487)
	at codechicken.nei.recipe.GuiUsageRecipe.openRecipeGui(GuiUsageRecipe.java:18)
	at codechicken.nei.recipe.RecipeItemInputHandler.lastKeyTyped(RecipeItemInputHandler.java:19)
	at codechicken.nei.guihook.GuiContainerManager.lastKeyTyped(GuiContainerManager.java:326)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73869_a(GuiContainer.java)
	at net.minecraft.client.gui.inventory.GuiContainer.public_func_73869_a(GuiContainer.java)
	at codechicken.nei.guihook.GuiContainerManager.callKeyTyped(GuiContainerManager.java)
	at codechicken.nei.guihook.GuiContainerManager.keyTyped(GuiContainerManager.java:525)
	at codechicken.nei.guihook.GuiContainerManager.handleKeyboardInput(GuiContainerManager.java:514)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146282_l(GuiContainer.java)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:519)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1699)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1056)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:369)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by HammerDave** [comment]
Same thing happens with dense coal.

**Comment by Kashdeya** [comment]
This is because nei is not supported in my mods because nei was not updated when I released my mods. I would suggest you use JEI which is by far a better mod.

**Comment by HammerDave** [comment]
Turns out it happens on other things too, and not a bug with your mods, sorry.  In fact the NEI "use" function doesn't seem to be working on much of anything.  Anyhow, if I can mark this as closed I will, and thanks for the reply!

However I must disagree regarding which one is "better", or at least which one will be better once they're both working.  NEI has functions that JEI (+FEI) don't have.  Strongly recommend supporting it at some point, in case people have a preference for those functions.  :)
